version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - "TZ=Japan"
    restart: always
    ports:
      - 80:80
      - 443:443
    tty: true
