version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./flask:/app
    # ports:
    #   - 5000:5000 # 内部だけでいいのでホストOSには出さない
    links:
      - db
    tty: true
